-- AlterTable
ALTER TABLE "RecordImage" ADD COLUMN     "focalX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "RecordImage" ADD COLUMN     "focalY" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "RecordImage" ADD COLUMN     "zoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
